[[redirects]]
  from = "/api/*"
  to = "http://Streamforge-env.eba-dy2x3vhi.us-east-1.elasticbeanstalk.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
